### PR TITLE
AT-2835: acceptance test fix and handling nesting

### PR DESCRIPTION
**Pull request by andras-mdc**

### CODE REVIEW

**Review by dankruse1 — COMMENTED** [review]
whats the behaviour if the nesting is NULL (no values)? Should we have a test scenario for this?

**Comment by jean-maldo** [comment]
Another scenario could also be if a DataFrame has nesting first, then repeated fields. That is also possible right? 

Example repeated first, then nesting:
SELECT
    CAST('111852565' AS STRING),
    [
        STRUCT(CAST('BBBEDE030GRY-UK' AS STRING), CAST('1' AS INT64)),
        STRUCT(CAST('CCCEDE030GRY-UK' AS STRING), CAST('2' AS INT64)),
        STRUCT(CAST('DDDEDE030GRY-UK' AS STRING), CAST('1' AS INT64))
    ],
    CAST('2021-01-01' AS DATE)

vs

Current example of nesting first, then with repeated:
SELECT
    CAST('101852564' AS STRING) AS order_reference,
        STRUCT([CAST('AAAEDE030GRY-UK' AS STRING, CAST('BBBEDE090GRY-UK' AS STRING]]) AS skus, 
        CAST('2' AS INT64) AS qty)
    AS order_lines,
    CAST('2021-01-01' AS DATE) AS date

Could add as a test case as well, or if out of scope can note it down.

**Comment by andras-mdc** [comment]
> whats the behaviour if the nesting is NULL (no values)? Should we have a test scenario for this?

works ok if the mock is correctly done - if you would leave it empty then the cte itself would break
[
STRUCT(CAST(NULL AS STRING), CAST(NULL AS INT64))
],

**Comment by andras-mdc** [comment]
> Another scenario could also be if a DataFrame has nesting first, then repeated fields. That is also possible right?
> 
> Current example repeated first, then nesting:
> SELECT
> CAST('111852565' AS STRING),
> [
> STRUCT(CAST('BBBEDE030GRY-UK' AS STRING), CAST('1' AS INT64)),
> STRUCT(CAST('CCCEDE030GRY-UK' AS STRING), CAST('2' AS INT64)),
> STRUCT(CAST('DDDEDE030GRY-UK' AS STRING), CAST('1' AS INT64))
> ],
> CAST('2021-01-01' AS DATE)
> 
> vs
> Example of nesting first, then with repeated:
> SELECT
> CAST('101852564' AS STRING) AS order_reference,
> STRUCT([CAST('AAAEDE030GRY-UK' AS STRING, CAST('BBBEDE090GRY-UK' AS STRING]]) AS skus,
> CAST('2' AS INT64) AS qty)
> AS order_lines,
> CAST('2021-01-01' AS DATE) AS date
> 
> Could add as a test case as well, or if out of scope can note it down.

in the flatten function i noted that it only handles single layer nesting, but yeah it could be a functionality later with a recursive function

**Comment by dankruse1** [comment]
how about a case like this:
```
SELECT
CAST('111852565' AS STRING),
[
STRUCT(CAST('BBBEDE030GRY-UK' AS STRING), CAST('1' AS INT64)),
STRUCT(CAST('CCCEDE030GRY-UK' AS STRING), CAST('2' AS INT64)),
STRUCT(CAST('DDDEDE030GRY-UK' AS STRING), CAST('1' AS INT64))
],
CAST('2021-01-01' AS DATE)
UNION ALL
SELECT
CAST('111852565' AS STRING),
[],
CAST('2021-01-01' AS DATE)
```
a real world example of this could be `eventstream.order_placed_v2.charges.coupon.code`
--

**Review by dankruse1 — APPROVED** [review]

**Pull request merged**
